package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DummyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDummyAllPropertiesEquals(Dummy expected, Dummy actual) {
        assertDummyAutoGeneratedPropertiesEquals(expected, actual);
        assertDummyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDummyAllUpdatablePropertiesEquals(Dummy expected, Dummy actual) {
        assertDummyUpdatableFieldsEquals(expected, actual);
        assertDummyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDummyAutoGeneratedPropertiesEquals(Dummy expected, Dummy actual) {
        assertThat(actual)
            .as("Verify Dummy auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDummyUpdatableFieldsEquals(Dummy expected, Dummy actual) {
        assertThat(actual)
            .as("Verify Dummy relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDummyUpdatableRelationshipsEquals(Dummy expected, Dummy actual) {
        // empty method
    }
}
